default:
  image: docker/compose:latest
before_script:
  - apk add --update nodejs npm
  
DockerSetup:

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

  # Official docker compose image.
  image:
    name: docker/compose:latest

  services:
    - docker:dind
  before_script:
    - docker version
    - docker-compose version
    - apk add --update nodejs npm

  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up -d 
    - cd tests/ && npm install
    - npm run test
    

